routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\customerController;

Route::get('/', function () {
    return view('welcome');
});

// Quản lý lớp => CRUD 
Route::resource('/customer', customerController::class);

// Quản lý sinh viên => CRUD 

app/Models/customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class customer extends Model
{
    use HasFactory;

    protected $table = 'customer';

    public $timestamps = false;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    
}

app/Http/Controllers/customerController.php
<?php

namespace App\Http\Controllers;

use App\Models\customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;


class customerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');

        $listCustomer = customer::where('name', 'like', "%$search%")->paginate(3);

        return view('customer.index', [
            "listCustomer" => $listCustomer,
            "search" => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate(
            [

                'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048|dimensions:min_width=100,min_height=100,max_width=2000,max_height=2000',

                'name' => 'required|max:255',

                'phone' => 'required',
                'email' => 'required|unique:customer',

            ],
            [

                'email.unique' => 'Email đã tồn tại!',

                'image.required' => 'Ảnh đại diện không được để trống',
                'name.required' => 'Họ tên không được để trống',

                'phone.required' => 'SĐT không được để trống',
                'email.required' => 'Email không được để trống',
                'gender.required' => 'Không được để trống phần giới tính',


            ]
        );

        // Nhận dữ liệu
        $image = $request->file('image');
        $name = $request->get('name');
        $gender = $request->get('gender');
        $phone = $request->get('phone');
        $email = $request->get('email');


        $customer = new customer();

        $new_image = time() . '.' . $image->getClientOriginalExtension();
        $request->image->move(public_path('images'), $new_image);

        $customer->image = $new_image;

        $customer->name = $name;
        $customer->gender = $gender;
        $customer->phone = $phone;
        $customer->email = $email;
        $customer->save();


        return Redirect::route('customer.index');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
}

resources/views/customer/create.blade.php
<h1>Thêm khách hàng</h1>
@if ($errors->any())

<div class="alert alert-danger">

    <ul>

        @foreach ($errors->all() as $error)

        <li>{{ $error }}</li>

        @endforeach

    </ul>

</div>

@endif
<form method="POST" action="{{route('customer.store')}}" enctype='multipart/form-data'>
    @csrf
    <table border="1">
        <tr>
            <td>Hình ảnh:</td>
            <td><input type="file" name="image"><br></td>
        </tr>
        <tr>
            <td>Tên khách hàng:</td>
            <td> <input type="text" required name="name"><br></td>
        </tr>
        <tr>
            <td>Giới tính:</td>
            <td> <input type="radio" name="gender" value="1">Nam
                <input type="radio" name="gender" value="0">Nữ<br>
            </td>
        </tr>
        <tr>
            <td>Số điện thoại:</td>
            <td> <input type="text" name="phone"><br></td>
        </tr>
        <tr>
            <td>Email:</td>
            <td> <input type="email" name="email"><br></td>
        </tr>

        <tr>
            <td><button>Submit</button></td>
        </tr>
    </table>
</form>

resources/views/customer/index.blade.php
<h1>Danh sách khách hàng</h1>
<a href="{{route('customer.create')}}">Thêm khách hàng</a>

<form action="" method="get">
    <input type="text" name="search" value="#">
    <button>Tìm nó</button>
</form>

<table>
    <tr>
        <th>Mã</th>
        <th>Ảnh</th>
        <th>Tên</th>
        <th>Giới tính</th>
        <th>Số điện thoại</th>
        <th>email</th>
    </tr>
    @foreach ($listCustomer as $customer)
    <tr>
        <td>{{ $customer->id_customer }}</td>
        <td><img src="{{ asset('images/' . $customer->image) }}" width="100px"></td>
        <td>{{ $customer->name }}</td>
        <td>{{ $customer->gender }}</td>
        <td>{{ $customer->phone }}</td>
        <td>{{ $customer->email }}</td>
    </tr>
    @endforeach
</table>

{{ $listCustomer->appends([
        'search' => $search,
    ])->links() }}